### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SuperDarkAqua**

### CODE REVIEW

**Comment by ghost** [comment]
Hi @SuperDarkAqua! Thank you for the pull request for your wonderful game and I enjoyed playing through it!

We don't accept pull requests for uploading game files directly to the repository and would instead prefer the `README.md` in the root of this repo to be modified. Sorry if this is a bit confusing if this is the first time you're using Github. So one way you can do this is after forking as you've done already, just click on the `README.md` in your fork and then click on edit:

image

Modify this file in the same way that the other games are listed. Then you can create another pull request since this one will likely have to be closed.

You can also delete the game file here:

image

If possible (if your collaborators are okay with it), please include the source/project files as a link as well. Github is preferred. You can see how Eternal set theirs up [here](https://github.com/EternalSeraph8/ppp_game).

Alternatively, you can submit links such as a Google Drive link in the comments here (a separate source one is nice too) and I'll work with what you've got.

We will consider making a `CONTRIBUTING.md` file in the future to make this more clear. Sorry for the inconvenience.

**Comment by ghost** [comment]
And just for your information, I found that it's possible to soft lock the game and in such a situation, the only way to kill the game is with task manager.

https://user-images.githubusercontent.com/107907582/192614168-8392ffb3-94db-4e4b-b0a7-ebadbe4d970e.mp4

In general, it's corner collisions that can be problematic I think.

https://user-images.githubusercontent.com/107907582/192614359-d6f5172b-d5d8-4990-8e4c-af956096c022.mp4

**Comment by SuperDarkAqua** [comment]
Hello,

I updated everything and tried to make the formatting as close as possible
to the one submitted by Eternal. Hopefully it is correct now, but if not,
please let me know.

Thank you for your help,
SuperDarkAqua

**Comment by SuperDarkAqua** [comment]
In addition, I believe I've fixed the soft lock issue, and the updated
version of the game should be available now.

**Comment by ghost** [comment]
Hello @SuperDarkAqua,

My apologies as I think I was a bit unclear in my last comment.

Firstly, if you have a new link to the new version/build of the game, you can send it as a Google Drive link as a response here, though I assume you've also had contact with management via email as well. You can share the same one sent to that email here since it will just be added to the list of games.

And then you can include a link to the entire project's source on Google Drive too (so that can be either the entire project folder with the scripts, assets, the `.yyp` file, etc in a zip archive or you can export the project using the built in exporter in GameMaker which will make a `.yyz` file).

These Google Drive links should be long lived to be listed so don't delete them please.

_**If**_ you'd like to include the project source as a GitHub repository link as is best practice, what you would do is go to your own GitHub profile and create a new repository there with a name relevant to your game. You would include the entire root of the project including the `.yyp` file among other scripts and assets in their respective folders. You can include your own `README.md` file there too. Then you can also include that GitHub repository link here in a message as well. (You can even include a build of the game using the [release feature](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) if you'd like instead of Google Drive links.)

Keep in mind that you providing the source is **_optional_** but greatly appreciated.

As for this current pull request, if you can provide some of the aforementioned links above, I will close it and make the modifications needed to list the game!

Really sorry for the confusion and I'll make sure that there are more clear instructions especially for other fans in the future 🙇‍♀️ Thank you so much for your time, for supporting PRISM Project talents, and even fixing the bug I had mentioned.

-Ramenkun

**Comment by SuperDarkAqua** [comment]
Thank you once again for all of your patience and help! Here are the
requested links. Hopefully they should actually be in order this time, and
if not, I'm REALLY sorry, again. Please let me know if it all looks good at
your earliest convenience.

Game zip file
<https://drive.google.com/file/d/1fvhLpzWDUCuDAN3KC5gVPswzxIh2jsce/view?usp=sharing>
Source file
<https://drive.google.com/drive/folders/1OD8_V1G9TRCBJZ3Efe_ryehbtaVUZc_U?usp=sharing>

**Comment by ghost** [comment]
You can see that it was added with this change: https://github.com/PRISMProj/awesome-prism-project-fan-apps/commit/8132a0ae5f8a097528f6d37d70bdce53ade3b30e

If you'd like to change the description or links, just let me know. But if everything looks good, I'll close this out 👍

**Comment by SuperDarkAqua** [comment]
Ah I see. Sorry for the misunderstanding! I'll get the entire project
folder uploaded to drive right away, and send the link to everything in
another email. I should hopefully have it done in the next hour or so!
Thanks again for your help!

**Comment by SuperDarkAqua** [comment]
It looks great! Thanks for all of your help too! You're my hero, Ramen-kun
🧎‍♂️🙇‍♂️

**Comment by SuperDarkAqua** [comment]
Thank you for your response! I'll make sure to get those files uploaded as
soon as possible. Sadly, I'm not sure I'll have time to fix the corner
collision, but I'll definitely try to do so if I find the time.

**Pull request closed without merging**
